/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment_test;

import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User10
 */
public class studentMenu extends javax.swing.JFrame {

    private boolean success;
    
    /**
     * Creates new form studentMenu
     */
    public studentMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnViewStudentDetails = new javax.swing.JButton();
        btnUpdateStudentDetails = new javax.swing.JButton();
        btnViewRoom = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnApplyRoom = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu for student");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(780, 440));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Please choose what do you want to do by using this system.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Student Menu");

        btnViewStudentDetails.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnViewStudentDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VSD.png"))); // NOI18N
        btnViewStudentDetails.setText("View student details ");
        btnViewStudentDetails.setToolTipText("");
        btnViewStudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentDetailsActionPerformed(evt);
            }
        });

        btnUpdateStudentDetails.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnUpdateStudentDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/USD.png"))); // NOI18N
        btnUpdateStudentDetails.setText("Update student details ");
        btnUpdateStudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentDetailsActionPerformed(evt);
            }
        });

        btnViewRoom.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnViewRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/VRD.png"))); // NOI18N
        btnViewRoom.setText("View room details ");
        btnViewRoom.setMaximumSize(new java.awt.Dimension(273, 65));
        btnViewRoom.setMinimumSize(new java.awt.Dimension(273, 65));
        btnViewRoom.setPreferredSize(new java.awt.Dimension(173, 77));
        btnViewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRoomActionPerformed(evt);
            }
        });

        btnPayment.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/MP.png"))); // NOI18N
        btnPayment.setText("  Make payment ");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnApplyRoom.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnApplyRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AR.png"))); // NOI18N
        btnApplyRoom.setText("Apply a room");
        btnApplyRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyRoomActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/LOGOUT.png"))); // NOI18N
        btnLogout.setText("Logout ");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewStudentDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnApplyRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnUpdateStudentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewStudentDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateStudentDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApplyRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewStudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentDetailsActionPerformed
        studentViewStudentDetails studentViewStudentDetails = new studentViewStudentDetails();
        studentViewStudentDetails.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnViewStudentDetailsActionPerformed

    private void btnUpdateStudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStudentDetailsActionPerformed
        studentUpdateDetails studentUpdateDetails = new studentUpdateDetails();
        studentUpdateDetails.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnUpdateStudentDetailsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        menu menu = new menu();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRoomActionPerformed
        studentViewRoom studentViewRoom = new studentViewRoom();
        studentViewRoom.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnViewRoomActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        studentPayment studentPayment = new studentPayment();
        studentPayment.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnPaymentActionPerformed

    roomDataIO checkID = new roomDataIO();
    FileWriter output;

    private void btnApplyRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyRoomActionPerformed
        String roomType = JOptionPane.showInputDialog(null, "Please enter the "
                + "room type ID you want.");
        try {
            if (checkID.checkID(roomType)) {
                String moveInDate = JOptionPane.showInputDialog(null, "Please enter your move in date. (dd/mm/yyyy)");
                if (moveInDate.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Move in date should not be empty. Please try again.");
                } else {
                    String studentID = new studentLogin().getStudentID();
                    writeToApplicationFile(studentID, roomType, moveInDate);
                    JOptionPane.showMessageDialog(null, "Room Applied successfully. You will be notified about your application within 10 working days through email.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Room Type ID not found. Please try again.");
            }
        } catch (IOException ex) {
            Logger.getLogger(studentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApplyRoomActionPerformed

    private void writeToApplicationFile(String studentID, String roomType, String moveInDate) throws IOException {
        LocalDate currentDate = LocalDate.now();
        try (FileWriter output = new FileWriter("application.txt", true)) {
            output.write(studentID + "!" + roomType + "!" + moveInDate + "!" + currentDate + "\n");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyRoom;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnUpdateStudentDetails;
    private javax.swing.JButton btnViewRoom;
    private javax.swing.JButton btnViewStudentDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
